import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import {
  SrsGeneratorService,
  SRSDocument,
  ElicitacionData,
  NegociacionItem,
  ValidacionInfo,
  ArtefactoInfo,
} from '../../services/srs-generator.service';
import { ProyectoActivoService } from '../../../../core/services/proyecto-activo.service';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-srs-generator',
  standalone: false,
  templateUrl: './srs-generator.component.html',
  styleUrls: ['./srs-generator.component.css'],
})
export class SrsGeneratorComponent implements OnInit, OnDestroy {
  srsData: SRSDocument = {
    projectName: '',
    introduction: '',
    stakeholders: [],
    users: [],
    functionalRequirements: [],
    nonFunctionalRequirements: [],
    useCases: [],
    constraints: [],
    elicitacion: { entrevistas: [], procesos: [], necesidades: [] },
    negociaciones: [],
    validacionInfo: null,
    artefactosInfo: [],
  };

  activeTab = 'introduction';
  proyectoId: number | null = null;
  proyectoNombre = '';
  proyectoCodigo = '';
  isLoading = false;
  isLoadingProject = false;
  isAutoGenerating = false;
  autoGenerated = false;

  private subscriptions = new Subscription();
  private readonly BASE_URL = 'http://localhost:8000';

  // Estados de guardado por item
  savingUsers: boolean[] = [];
  savingUseCases: boolean[] = [];
  savingConstraints: boolean[] = [];
  userMessages: string[] = [];
  useCaseMessages: string[] = [];
  constraintMessages: string[] = [];

  // Tabs disponibles
  tabs = [
    { id: 'introduction', label: 'Introduccion', icon: '' },
    { id: 'stakeholders', label: 'Stakeholders', icon: '' },
    { id: 'elicitacion', label: 'Elicitacion', icon: '' },
    { id: 'rf', label: 'RF', icon: '' },
    { id: 'rnf', label: 'RNF', icon: '' },
    { id: 'users', label: 'Usuarios', icon: '' },
    { id: 'usecases', label: 'Casos de Uso', icon: '' },
    { id: 'constraints', label: 'Restricciones', icon: '' },
    { id: 'negociacion', label: 'Negociacion', icon: '' },
    { id: 'validacion', label: 'Validacion', icon: '' },
    { id: 'artefactos', label: 'Artefactos', icon: '' },
  ];

  constructor(
    private srsService: SrsGeneratorService,
    private route: ActivatedRoute,
    private router: Router,
    private http: HttpClient,
    private proyectoActivoService: ProyectoActivoService
  ) {}

  ngOnInit(): void {
    this.obtenerProyectoId();
  }

  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
  }

  // ══════════════════════════════════════════════════════════════════════
  //  RESOLUCIÓN DE PROYECTO
  // ══════════════════════════════════════════════════════════════════════

  private obtenerProyectoId(): void {
    const id = this.proyectoActivoService.proyectoId;
    if (id) {
      this.proyectoId = Number(id);
      this.cargarTodosLosDatos();
      return;
    }
    this.route.params.subscribe((params: any) => {
      if (params?.['proyectoId']) {
        this.proyectoId = parseInt(params['proyectoId'], 10);
        this.cargarTodosLosDatos();
      }
    });
    setTimeout(() => {
      if (!this.proyectoId) {
        const stored = sessionStorage.getItem('proyectoActualId');
        if (stored) {
          this.proyectoId = parseInt(stored, 10);
          this.cargarTodosLosDatos();
        }
      }
    }, 500);
  }

  // ══════════════════════════════════════════════════════════════════════
  //  AUTO-GENERAR SRS DESDE TODOS LOS MÓDULOS
  // ══════════════════════════════════════════════════════════════════════

  autoGenerarSrs(): void {
    if (!this.proyectoId) return;
    this.isAutoGenerating = true;

    this.srsService.autoGenerarSrs(this.proyectoId).subscribe({
      next: (response: any) => {
        const data = response?.data || response;
        this.mapearSrsDesdeBackend(data);
        this.autoGenerated = true;
        this.isAutoGenerating = false;
      },
      error: (err) => {
        console.error('Error al auto-generar SRS:', err);
        this.isAutoGenerating = false;
        alert('Error al auto-generar el SRS. Verifica la consola.');
      },
    });
  }

  private mapearSrsDesdeBackend(data: any): void {
    this.srsData.projectName = data.nombre_documento || this.srsData.projectName;
    this.srsData.introduction = data.introduccion || '';

    // Stakeholders
    this.srsData.stakeholders = (data.stakeholders || []).map((s: any) => ({
      name: s.name || '',
      role: s.role || '',
      responsibility: s.responsibility || '',
    }));

    // Usuarios
    this.srsData.users = (data.usuarios || []).map((u: any) => ({
      userId: u.userId || '',
      userType: u.userType || '',
      description: u.description || '',
    }));
    this.savingUsers = this.srsData.users.map(() => false);
    this.userMessages = this.srsData.users.map(() => '');

    // RF
    this.srsData.functionalRequirements = (data.requerimientos_funcionales || []).map((r: any) => ({
      rfId: r.rfId || '',
      description: r.description || '',
      priority: r.priority || 'Media',
    }));

    // RNF
    this.srsData.nonFunctionalRequirements = (data.requerimientos_no_funcionales || []).map((r: any) => ({
      rnfId: r.rnfId || '',
      category: r.category || '',
      description: r.description || '',
    }));

    // Casos de uso
    this.srsData.useCases = (data.casos_uso || []).map((c: any) => ({
      useCase: c.useCase || '',
      actors: c.actors || [],
      description: c.description || '',
      steps: c.steps || [],
    }));
    this.savingUseCases = this.srsData.useCases.map(() => false);
    this.useCaseMessages = this.srsData.useCases.map(() => '');

    // Restricciones
    this.srsData.constraints = (data.restricciones || []).map((r: any) => ({
      constraintId: r.constraintId || '',
      type: r.type || '',
      description: r.description || '',
    }));
    this.savingConstraints = this.srsData.constraints.map(() => false);
    this.constraintMessages = this.srsData.constraints.map(() => '');

    // Elicitación
    const eli = data.elicitacion || {};
    this.srsData.elicitacion = {
      entrevistas: eli.entrevistas || [],
      procesos: eli.procesos || [],
      necesidades: eli.necesidades || [],
    };

    // Negociaciones
    this.srsData.negociaciones = (data.negociaciones || []).map((n: any) => ({
      nombre: n.nombre || '',
      descripcion: n.descripcion || '',
      prioridad: n.prioridad || 'Media',
      aceptado: !!n.aceptado,
    }));

    // Validación
    this.srsData.validacionInfo = data.validacion_info || null;

    // Artefactos
    this.srsData.artefactosInfo = (data.artefactos_info || []).map((a: any) => ({
      nombre: a.nombre || '',
      categoria: a.categoria || '',
      descripcion: a.descripcion || '',
      nombre_archivo: a.nombre_archivo || '',
      tipo_mime: a.tipo_mime || '',
    }));
  }

  // ══════════════════════════════════════════════════════════════════════
  //  CARGA MANUAL DE DATOS (fallback si no se usa auto-generar)
  // ══════════════════════════════════════════════════════════════════════

  private cargarTodosLosDatos(): void {
    if (!this.proyectoId) return;
    this.isLoadingProject = true;
    this.cargarProyecto();
    this.cargarStakeholders();
    this.cargarUsuarios();
    this.cargarRequerimientosFuncionales();
    this.cargarRequerimientosNoFuncionales();
    this.cargarCasosDeUso();
    this.cargarRestricciones();
    this.cargarElicitacion();
    this.cargarNegociaciones();
    this.cargarValidacion();
    this.cargarArtefactos();

    setTimeout(() => {
      this.isLoadingProject = false;
    }, 2500);
  }

  private cargarProyecto(): void {
    if (!this.proyectoId) return;
    this.http.get<any>(`${this.BASE_URL}/proyectos/${this.proyectoId}`).subscribe(
      (res) => {
        const p = res?.data || res;
        this.proyectoNombre = p.nombre || '';
        this.proyectoCodigo = p.codigo || '';
        this.srsData.projectName = `${this.proyectoNombre} - SRS v1.0`;
        if (p.descripcion_problema) this.srsData.introduction = p.descripcion_problema;
        else if (p.objetivo_general) this.srsData.introduction = p.objetivo_general;
      },
      () => {}
    );
  }

  private cargarStakeholders(): void {
    if (!this.proyectoId) return;
    this.http.get<any>(`${this.BASE_URL}/stakeholders/?proyecto_id=${this.proyectoId}`).subscribe(
      (res) => {
        const list = Array.isArray(res) ? res : res?.data || [];
        this.srsData.stakeholders = list.map((s: any) => ({
          name: s.nombre || s.name || '',
          role: s.rol || s.role || '',
          responsibility: `Tipo: ${s.tipo || 'N/A'}, Area: ${s.area || 'N/A'}, Influencia: ${s.nivel_influencia || 'N/A'}`,
        }));
      },
      () => {}
    );
  }

  private cargarUsuarios(): void {
    if (!this.proyectoId) return;
    this.http.get<any>(`${this.BASE_URL}/tipo-usuario/?proyecto_id=${this.proyectoId}`).subscribe(
      (res) => {
        const list = Array.isArray(res) ? res : res?.data || [];
        this.srsData.users = list.map((u: any) => ({
          backendId: u.id_tipo_usuario || u.id || undefined,
          userId: String(u.id_tipo_usuario || u.id || ''),
          userType: u.tipo || u.userType || '',
          description: u.descripcion || u.description || '',
        }));
        this.savingUsers = this.srsData.users.map(() => false);
        this.userMessages = this.srsData.users.map(() => '');
      },
      () => {}
    );
  }

  private cargarRequerimientosFuncionales(): void {
    if (!this.proyectoId) return;
    this.http.get<any>(`${this.BASE_URL}/api/requerimientos-funcionales/?proyecto_id=${this.proyectoId}`).subscribe(
      (res) => {
        const list = Array.isArray(res) ? res : res?.data || [];
        this.srsData.functionalRequirements = list.map((r: any) => ({
          rfId: r.codigo || r.rfId || '',
          description: r.descripcion || r.description || '',
          priority: r.prioridad || r.priority || 'Media',
        }));
      },
      () => {}
    );
  }

  private cargarRequerimientosNoFuncionales(): void {
    if (!this.proyectoId) return;
    this.http.get<any>(`${this.BASE_URL}/rnf/?proyecto_id=${this.proyectoId}`).subscribe(
      (res) => {
        const list = Array.isArray(res) ? res : res?.data || [];
        this.srsData.nonFunctionalRequirements = list.map((r: any) => ({
          rnfId: r.codigo || r.rnfId || '',
          category: r.tipo || r.category || '',
          description: r.descripcion || r.description || '',
        }));
      },
      () => {}
    );
  }

  private cargarCasosDeUso(): void {
    if (!this.proyectoId) return;
    this.http.get<any>(`${this.BASE_URL}/api/casos-uso/?proyecto_id=${this.proyectoId}`).subscribe(
      (res) => {
        const list = Array.isArray(res) ? res : res?.data || [];
        this.srsData.useCases = list.map((c: any) => ({
          backendId: c.id_caso_uso || c.id || undefined,
          useCase: c.nombre || c.useCase || '',
          actors: Array.isArray(c.actores) ? c.actores : [],
          description: c.descripcion || c.description || '',
          steps: Array.isArray(c.pasos) ? c.pasos : [],
        }));
        this.savingUseCases = this.srsData.useCases.map(() => false);
        this.useCaseMessages = this.srsData.useCases.map(() => '');
      },
      () => {}
    );
  }

  private cargarRestricciones(): void {
    if (!this.proyectoId) return;
    this.http.get<any>(`${this.BASE_URL}/api/restricciones/?proyecto_id=${this.proyectoId}`).subscribe(
      (res) => {
        const list = Array.isArray(res) ? res : res?.data || [];
        this.srsData.constraints = list.map((r: any) => ({
          backendId: r.id_restriccion || r.id || undefined,
          constraintId: r.codigo || r.constraintId || '',
          type: r.tipo || r.type || '',
          description: r.descripcion || r.description || '',
        }));
        this.savingConstraints = this.srsData.constraints.map(() => false);
        this.constraintMessages = this.srsData.constraints.map(() => '');
      },
      () => {}
    );
  }

  private cargarElicitacion(): void {
    if (!this.proyectoId) return;
    this.http.get<any>(`${this.BASE_URL}/api/elicitacion/resumen?proyecto_id=${this.proyectoId}`).subscribe(
      (res) => {
        // El resumen solo da conteos, necesitamos los datos completos
      },
      () => {}
    );
    // Entrevistas
    this.http.get<any>(`${this.BASE_URL}/api/elicitacion/entrevistas?proyecto_id=${this.proyectoId}`).subscribe(
      (res) => {
        const list = Array.isArray(res) ? res : res?.data || [];
        this.srsData.elicitacion.entrevistas = list.map((e: any) => ({
          pregunta: e.pregunta || '',
          respuesta: e.respuesta || '',
          observaciones: e.observaciones || '',
        }));
      },
      () => {}
    );
    // Procesos
    this.http.get<any>(`${this.BASE_URL}/api/elicitacion/procesos?proyecto_id=${this.proyectoId}`).subscribe(
      (res) => {
        const list = Array.isArray(res) ? res : res?.data || [];
        this.srsData.elicitacion.procesos = list.map((p: any) => ({
          nombre_proceso: p.nombre_proceso || '',
          descripcion: p.descripcion || '',
          problemas_detectados: p.problemas_detectados || '',
        }));
      },
      () => {}
    );
    // Necesidades
    this.http.get<any>(`${this.BASE_URL}/api/elicitacion/necesidades?proyecto_id=${this.proyectoId}`).subscribe(
      (res) => {
        const list = Array.isArray(res) ? res : res?.data || [];
        this.srsData.elicitacion.necesidades = list
          .filter((n: any) => n.seleccionada)
          .map((n: any) => ({ nombre: n.nombre || '' }));
      },
      () => {}
    );
  }

  private cargarNegociaciones(): void {
    if (!this.proyectoId) return;
    this.http.get<any>(`${this.BASE_URL}/api/negociaciones/?proyecto_id=${this.proyectoId}`).subscribe(
      (res) => {
        const list = Array.isArray(res) ? res : res?.data || [];
        this.srsData.negociaciones = list.map((n: any) => ({
          nombre: n.nombre || '',
          descripcion: n.descripcion || '',
          prioridad: n.prioridad || 'Media',
          aceptado: !!n.aceptado,
        }));
      },
      () => {}
    );
  }

  private cargarValidacion(): void {
    if (!this.proyectoId) return;
    this.http.get<any>(`${this.BASE_URL}/api/validaciones/proyecto/${this.proyectoId}`).subscribe(
      (res) => {
        const v = res?.data || res;
        if (v && v.id_validacion) {
          this.srsData.validacionInfo = {
            aprobado: v.aprobado,
            aprobador: v.aprobador || '',
            observaciones: v.observaciones || '',
            checklist_rf: v.checklist_rf,
            checklist_rnf: v.checklist_rnf,
            checklist_casos_uso: v.checklist_casos_uso,
            checklist_restricciones: v.checklist_restricciones,
            checklist_prioridades: v.checklist_prioridades,
          };
        }
      },
      () => {}
    );
  }

  private cargarArtefactos(): void {
    if (!this.proyectoId) return;
    this.http.get<any>(`${this.BASE_URL}/api/artefactos/?proyecto_id=${this.proyectoId}`).subscribe(
      (res) => {
        const list = Array.isArray(res) ? res : res?.data || [];
        this.srsData.artefactosInfo = list.map((a: any) => ({
          nombre: a.nombre || '',
          categoria: a.categoria || '',
          descripcion: a.descripcion || '',
          nombre_archivo: a.nombre_archivo || '',
          tipo_mime: a.tipo_mime || '',
        }));
      },
      () => {}
    );
  }

  // ══════════════════════════════════════════════════════════════════════
  //  HELPERS DE CONTEO para el dashboard
  // ══════════════════════════════════════════════════════════════════════

  getTabCount(tabId: string): number {
    switch (tabId) {
      case 'stakeholders': return this.srsData.stakeholders.length;
      case 'elicitacion':
        return (this.srsData.elicitacion?.entrevistas?.length || 0) +
               (this.srsData.elicitacion?.procesos?.length || 0) +
               (this.srsData.elicitacion?.necesidades?.length || 0);
      case 'rf': return this.srsData.functionalRequirements.length;
      case 'rnf': return this.srsData.nonFunctionalRequirements.length;
      case 'users': return this.srsData.users.length;
      case 'usecases': return this.srsData.useCases.length;
      case 'constraints': return this.srsData.constraints.length;
      case 'negociacion': return this.srsData.negociaciones.length;
      case 'validacion': return this.srsData.validacionInfo ? 1 : 0;
      case 'artefactos': return this.srsData.artefactosInfo.length;
      default: return 0;
    }
  }

  // ══════════════════════════════════════════════════════════════════════
  //  CRUD EXISTENTE (sin cambios)
  // ══════════════════════════════════════════════════════════════════════

  addStakeholder(): void { this.srsData.stakeholders.push({ name: '', role: '', responsibility: '' }); }
  removeStakeholder(i: number): void { this.srsData.stakeholders.splice(i, 1); }
  addFunctionalRequirement(): void { this.srsData.functionalRequirements.push({ rfId: '', description: '', priority: 'Media' }); }
  removeFunctionalRequirement(i: number): void { this.srsData.functionalRequirements.splice(i, 1); }
  addNonFunctionalRequirement(): void { this.srsData.nonFunctionalRequirements.push({ rnfId: '', category: '', description: '' }); }
  removeNonFunctionalRequirement(i: number): void { this.srsData.nonFunctionalRequirements.splice(i, 1); }

  addUser(): void {
    this.srsData.users.push({ backendId: undefined, userId: '', userType: '', description: '' });
    this.savingUsers.push(false);
    this.userMessages.push('');
  }

  guardarUsuario(i: number): void {
    if (!this.proyectoId) return;
    const user = this.srsData.users[i];
    if (!user.userType.trim()) { this.userMessages[i] = 'El tipo de usuario es requerido'; return; }
    this.savingUsers[i] = true;
    this.userMessages[i] = '';
    const payload = { proyecto_id: this.proyectoId, tipo: user.userType, descripcion: user.description };
    if (user.backendId) {
      this.http.put<any>(`${this.BASE_URL}/tipo-usuario/${user.backendId}`, payload).subscribe({
        next: () => { this.savingUsers[i] = false; this.userMessages[i] = 'Guardado'; setTimeout(() => this.userMessages[i] = '', 2000); },
        error: () => { this.savingUsers[i] = false; this.userMessages[i] = 'Error al guardar'; },
      });
    } else {
      this.http.post<any>(`${this.BASE_URL}/tipo-usuario/`, payload).subscribe({
        next: (r) => { const c = r?.data || r; this.srsData.users[i].backendId = c.id_tipo_usuario || c.id; this.savingUsers[i] = false; this.userMessages[i] = 'Creado'; setTimeout(() => this.userMessages[i] = '', 2000); },
        error: () => { this.savingUsers[i] = false; this.userMessages[i] = 'Error al crear'; },
      });
    }
  }

  removeUser(i: number): void {
    const user = this.srsData.users[i];
    const rm = () => { this.srsData.users.splice(i, 1); this.savingUsers.splice(i, 1); this.userMessages.splice(i, 1); };
    if (user.backendId) { this.http.delete(`${this.BASE_URL}/tipo-usuario/${user.backendId}`).subscribe({ next: rm, error: rm }); } else { rm(); }
  }

  addUseCase(): void {
    this.srsData.useCases.push({ backendId: undefined, useCase: '', actors: [], description: '', steps: [] });
    this.savingUseCases.push(false);
    this.useCaseMessages.push('');
  }

  guardarCasoDeUso(i: number): void {
    if (!this.proyectoId) return;
    const uc = this.srsData.useCases[i];
    if (!uc.useCase.trim()) { this.useCaseMessages[i] = 'El nombre es requerido'; return; }
    this.savingUseCases[i] = true;
    this.useCaseMessages[i] = '';
    const payload = { proyecto_id: this.proyectoId, nombre: uc.useCase, actores: uc.actors, descripcion: uc.description, pasos: uc.steps };
    if (uc.backendId) {
      this.http.put<any>(`${this.BASE_URL}/api/casos-uso/${uc.backendId}`, payload).subscribe({
        next: () => { this.savingUseCases[i] = false; this.useCaseMessages[i] = 'Guardado'; setTimeout(() => this.useCaseMessages[i] = '', 2000); },
        error: () => { this.savingUseCases[i] = false; this.useCaseMessages[i] = 'Error'; },
      });
    } else {
      this.http.post<any>(`${this.BASE_URL}/api/casos-uso/`, payload).subscribe({
        next: (r) => { const c = r?.data || r; this.srsData.useCases[i].backendId = c.id_caso_uso || c.id; this.savingUseCases[i] = false; this.useCaseMessages[i] = 'Creado'; setTimeout(() => this.useCaseMessages[i] = '', 2000); },
        error: () => { this.savingUseCases[i] = false; this.useCaseMessages[i] = 'Error'; },
      });
    }
  }

  removeUseCase(i: number): void {
    const uc = this.srsData.useCases[i];
    const rm = () => { this.srsData.useCases.splice(i, 1); this.savingUseCases.splice(i, 1); this.useCaseMessages.splice(i, 1); };
    if (uc.backendId) { this.http.delete(`${this.BASE_URL}/api/casos-uso/${uc.backendId}`).subscribe({ next: rm, error: rm }); } else { rm(); }
  }

  addStep(i: number): void { this.srsData.useCases[i].steps.push(''); }
  removeStep(i: number, j: number): void { this.srsData.useCases[i].steps.splice(j, 1); }
  updateActors(i: number, event: Event): void {
    const input = event.target as HTMLInputElement;
    this.srsData.useCases[i].actors = input.value.split(',').map(a => a.trim()).filter(a => a.length > 0);
  }

  addConstraint(): void {
    this.srsData.constraints.push({ backendId: undefined, constraintId: '', type: '', description: '' });
    this.savingConstraints.push(false);
    this.constraintMessages.push('');
  }

  guardarRestriccion(i: number): void {
    if (!this.proyectoId) return;
    const c = this.srsData.constraints[i];
    if (!c.type.trim() && !c.description.trim()) { this.constraintMessages[i] = 'Ingresa tipo o descripcion'; return; }
    this.savingConstraints[i] = true;
    this.constraintMessages[i] = '';
    const payload = { proyecto_id: this.proyectoId, codigo: c.constraintId, tipo: c.type, descripcion: c.description };
    if (c.backendId) {
      this.http.put<any>(`${this.BASE_URL}/api/restricciones/${c.backendId}`, payload).subscribe({
        next: () => { this.savingConstraints[i] = false; this.constraintMessages[i] = 'Guardado'; setTimeout(() => this.constraintMessages[i] = '', 2000); },
        error: () => { this.savingConstraints[i] = false; this.constraintMessages[i] = 'Error'; },
      });
    } else {
      this.http.post<any>(`${this.BASE_URL}/api/restricciones/`, payload).subscribe({
        next: (r) => { const cr = r?.data || r; this.srsData.constraints[i].backendId = cr.id_restriccion || cr.id; this.srsData.constraints[i].constraintId = cr.codigo || ''; this.savingConstraints[i] = false; this.constraintMessages[i] = 'Creado'; setTimeout(() => this.constraintMessages[i] = '', 2000); },
        error: () => { this.savingConstraints[i] = false; this.constraintMessages[i] = 'Error'; },
      });
    }
  }

  removeConstraint(i: number): void {
    const c = this.srsData.constraints[i];
    const rm = () => { this.srsData.constraints.splice(i, 1); this.savingConstraints.splice(i, 1); this.constraintMessages.splice(i, 1); };
    if (c.backendId) { this.http.delete(`${this.BASE_URL}/api/restricciones/${c.backendId}`).subscribe({ next: rm, error: rm }); } else { rm(); }
  }

  // ══════════════════════════════════════════════════════════════════════
  //  PDF
  // ══════════════════════════════════════════════════════════════════════

  async generatePDF(): Promise<void> {
    if (!this.proyectoId) { alert('No hay proyecto seleccionado.'); return; }
    if (!this.srsData.projectName.trim()) { alert('Ingresa el nombre del documento.'); return; }
    this.isLoading = true;
    try {
      await this.srsService.generateSRSPdf(this.srsData, this.proyectoId);
    } finally {
      this.isLoading = false;
    }
  }

  setActiveTab(tab: string): void {
    this.activeTab = tab;
  }
}
